### ISSUE TITLE
j.parameter: attrui displaying value is not properly updated

### ISSUE THREAD

**Issue by lossius** [jamoma/JamomaMax#828]
The below patch illustrates how the value attribute gets dynamically updated, but the changes does not show up in attrui.

<pre><code>
----------begin_max5_patcher----------
512.3oc0UssbaCBD8YouBFdVICHqKs8o7ejoSFrz5D7HAZPHWmIS92iXQ1Qt
MVV0sw08EXXYY2ydX4vKgAzk5sPKk7Mx8jffWBCBPSNCACqCn0hsEUhVzM5p
JspqlF42R2Yq.q84FvGCJMhPWJTORIeevkdukpdmviyGL1HrEOIUO9fAJr9i
tHO9VVDINMyMkxvE8l1GnFgQTCVv7.nDKqvLxF1SVhfSub8Mb9Nv0XfVPYEV
oVcPh39Dk5lXCCiwqupP.GOXck1TKv.jMXo09rGCTpyvqggtgn+0zXLO+uCM
xnWTBQA+nOs6xoE1hwlZIkc0MGkmvM+s4HdVhiV3LjiRx+ENZDOj8wz.++ht
fju9m0DjdUzCX5SMP1Hp5fIopiPSwmVyggJB4roZDhmlK9Tp702t+hhrRqI2
4pXRITHqEUmCWb5VFd5Wvo7joHC9mIYHrVSm73k2d.4bDOwA8Fy9CGF682H7
zIu7WbNp.XfnUR0O+CKBFm8CIgVcmoXWUNzxQdGNkPqUpveyF4i66tQN8jrr
DTieNWJacuvwZg8g2FyEN74.G1ECNYyANWLzjNCzjcUglKG2r3pBMtLwOAZh
OSz3exKZZ1.l1gPh.oWgasFEqxivkRkeIFQpA1H24+BzhvzqWY6Eq5LdkksY
IT+Q0kfQ0KP5DfBcY90v23FMvtF
-----------end_max5_patcher-----------
</code></pre>

**Comment by theod** [comment]
sending a message "value x" updates the attire object because it calls wrappedModularClass_attrSet function. It is not the case when we send just an int, a float or a list as it directly sends the value to the C++ Data wrapped class. 

a solution would be to use wrappedModularClass_attrSet in any case (hoping this will not increase cpu ... @tap ?)

<pre><code>
----------begin_max5_patcher----------
561.3oc0VEsaaBCE8Y3qvxZOlEYCw.cRaZ+GSSUNfSpi.ajwjkpp9uO70PSa
ChjfRq1xCN1G6b84b3dujmBCvq0GDMXz2P+BED7TXP..4.B5WGfq3GxK4Mvw
v45pJgxhW32yJNXA7u+iAnZtM+AoZ68FQt0GZJa0RxBD8N2XTLLRVRP+t+mH
KfXnWu6qqFBipsRpJEV3ZoGA0s1ATROZi8wRADArC34vP2vhKTQaJ0cgcB1m
lAjGFYDf7QiSdZxjrula3UBqvbuPwW6o7fF1nMUb3BSFUqQmp0dD+grOVK7z
saCDdMWsE+BEWuMWWpM98AEPVxRIqRibyHwwQwcynNQMCCrRzzv2JNIkXOur
Uf9B8rVq2TYISZsimXDMpYQuByZVR9r4L9TcZL6BRZH+ikz7A5GWPMD6+hRn
DVBKN1U8PS69j3lE0M8t4WFoD+oS+mTEsa4KZFsQqQ+zQSTgHWVwKOuiSnvW
oqlLE7JZ5dkt37xm3VqoUNk5xRNlPQmNiJ9JT2.pi.Gahgma+DfN3Ro58ujE
jjC+slPit0jODp9pAzQQUHZrRE2J0pWcF5aNyCxhBg500EExFWoBXHjQeXbo
rI9FvlJYQsVprMCoorkrEnL3AYT1v7iWxMi7tWNed1u5SyLe2UcSbyrzOKy7
R3NYldoupgWWuWXZ5iIvjtlD678fSW.KkJ+RHhXiXub37L.ga5ZbX65ZzZ70
sGx7+EMbktPXTc8XbE8gta94v+hDKDHD
-----------end_max5_patcher-----------
</code></pre>

**Comment by tap** [comment]
I think calling the attr set is *probably* okay.  Perhaps better is that after setting the value you could just call `attr_touch()`.

**Comment by theod** [comment]
nice ! I didn't know about attr_touch
I close the issue
