### ISSUE TITLE
using typeroute~ requires Max 7

### ISSUE THREAD

**Issue by avilleret** [jamoma/JamomaMax#832]
In the latest BETA release `[output~.model]` which is widely used relies on `[typeroute~]` which was introduce in Max7.
Thus most of all audio example needs Max7 to run.
I think it's a shame because I don't plan to use Max7 for now (and I guess I'm not the only one).
Isn't possible possible to replace it with something else ?

**Comment by bltzr** [comment]
I think this has been done by @lossius - so please, feel free to react, Trond.

We discussed in a BoD, a while ago, the question of making models Max7-only after a certain point, and that we would keep a version of Max-6 compatible models in a separated distro.  
We agreed that this should happen after separater packages have been split between externals and models/modules, in order to keep compatibility with Max6. But apparently this has been done before the split... maybe a solution would be to roll back to the first Max7-only commit, and create a the Max6-modules distro from then ?

The Max7 move was particularly the case for OpenGL models, because of the new GL context management, so I'm wondering if this change has been done already... @reno- @matcham ???

Though, as a workaround, you can use the patcher snippet below to replace typeroute~
On a side note, I think that typeroute~s should be on both inlets, as demonstrated in the patcher (and also that there should be a third inlet, but that's another debate...)

(Also, FYI, the reason for putting typeroute~ instead of j.in~s is that putting j.in~ in the patcher would automatically add mix and gain services, which are not desirable in this case - IMHO, this should be documented in the model, because it might seem a bit strange...) 

<pre><code>
----------begin_max5_patcher----------
706.3ocyV0zbaBCD8L9WgFcpcFpGPfC18TxugdLISGYPIYy.RLRhDmlI82d0
GfwI0oF2hI8h.srH8za28s54YA30hMLEF8UzknffmmED3LYMDzNO.WQ2jWRU
N2v.ujowg9u.ENah02+k3jNi0Rlhw0TMH3eWxx09kOkPlGEhxRsiQsCnqa+I
Qi1rt5mpYduw3seRoepzYE2sC7lJGLbHJp2neQbVi6.CUmeGvucO.4L6HYQ2
318KWTUYvueGsldY1L6P3.YHN6QCgzgUMaieoLzRMiWfTvsbZ4dXvkGf.Iqb
XMN5rQlAiOVFjrJwijU1GKciVREc83QWRCTXuOYEGML1JKYfjU3QPXj8RXjC
RX9Tt33SBgcv7qL7zmoj7gmnjf+XB4IiXD+8zbI3oW8zetRVMIhmTNW3qrce
7aTcizME8oBPoER66eFwt4FC9l+aoFps9+y4UhBVIp2B5bpAnfFXJDWvY6id
idW9sKca22N5boaDbsB9gyyXaOodybC3bKvERnOs90AojCV1k550RxNI0c22
RomWvT4Rn1QpWgu.cKiyjPNh1T.BjAv0MZj22GA8cn0MPoFAbTEUoYxchIgn
RnBL1BQTiRl47HjElSFhtFJcgp4WskRKAt46M9bMxd5PrXbp7iGmn0eRpnsc
JwEtRR8UXKFYwhUGJY9jIYz18KM5H0LbN3hyu4Fpt8vZ+0zfRzHy6NTc2IE0
uOlDUMv2JmbYedxNNcGTTv36dNMJMz0kLGSFs2.xfwiQPAE++CdVN.5g7ZLe
JgypgDshl1n0gvyxICNYCMXMMvYHkVYSJZ9mKrpfhZAv0spMwoj4KrWdM09H
MpeV+FMZG.x.nyj+R5zqiRqqefIUsKoCHlFG2Kj1oYgto.2O0shXI6Anye2k
MvToQaWaD1aj9FDaNKE6+US+cIuAbsBlY24Wl8K.GJjzsB
-----------end_max5_patcher-----------
</code></pre>

**Comment by avilleret** [comment]
one solution I see is to provide abstraction to replace Max7 only feature, as far as possible. 
and when it's not easy, then it's time to switch.
In this particular case of `[typeroute~]` it is very easy to provide a Max6 compatible abstraction.

**Comment by lossius** [comment]
It was quite a few months ago that this was discussed.

For me it makes absolutely no sense to not take advantage of the improvements that Max 7 has to offer, and instead design models etc. in such a way that they are already outdated. I don't see any reasons for not using Max 7, except if someone has not afforded the upgrade.

**Comment by avilleret** [comment]
> except if someone has not afforded the upgrade

which is my case
actually I'm working with Jamoma on Max6 using an iLok key a production studio give me.
so i'll need to upgrade, but since I don't use it for myself, I'll have to rise some funding to get an upgrade.

btw, I do think it's necessary to update the [Jamoma alpha download page](http://jamoma.org/download/0.6/) to reflects Max7 requirement.

**Comment by bltzr** [comment]
adding a typeroute~ abstraction seems a good idea…

apart from that, does anyone know about the GL modules ?

**Comment by lossius** [comment]
Sounds like a BOD topic. I'm very strongly favouring making use of Max 7 features. The improvement to OpenGL is one of *the* major improvements of Max 7, and it seems very backwards not to make use of it.

**Comment by avilleret** [comment]
I have no problem using Max7 if you buy me license.
A silly external easily replaceable by an abstraction such as typeroute~ is not a "major improvement" to my eyes.
Btw I could understand the need to use Max7 for OpenGL stuff.
Moreover this small thing makes Jamoma not working with earlier version of Max, so at least there should be a warning somewhere, on the download page for example.

**Comment by theod** [comment]
I think we should decide a policy for the 1.0 in order to clearly say if we still support Max6 or Max5 or not.
I put it into 1.0/external milestone to not forget this point before doing the release.

**Comment by theod** [comment]
the recent fix for stand alone feature have definitely banished the use of Max 6 or earlier version of Max closing radically the discussion ;-)
