### ISSUE TITLE
`[j.parameter]` send 0.0 on load even if no default value is set.

### ISSUE THREAD

**Issue by avilleret** [jamoma/JamomaMax#845]
`[j.parameter]` send 0.0 on load even if no default is set.
Is this the wanted behavior ?

<pre><code>
----------begin_max5_patcher----------
309.3ocqRErSCCCC8b5WQTNWlV6llFbiuCzDJq0v7TWRUh6nvz92IwoA11IP
vglH+7K1umcOUHTasifWIeP9jTHNUHDLTDPLEKTGziMcZOSSYf2ra2qJSoHX
jX3dGZnL5KVCYzG.NyiNT2kyfsLVnB2Umw50TyNz75yNngRRYQ07YyKkUKuO
dsXY7rN.I2L8FyvAzzADqopKZqG+faaUc3Mew0NPYxyifmKJhGk+MOueVu1E
rIANIA9em8q9A1uZU759+S6WOglfn26gTKUpxvmbyESGtapNzb6OHrhi3WOx
71AWStbSVT9slaCSHznIzZtfS8Ub1gss.mNq9Vzq21As2t5RhS22eDb9oRxB
Ir41acwvUkbHZRg7XR4fiXl+ZFQ6BieJL6GboM135UphXeNW7IvEwqa9
-----------end_max5_patcher-----------
</code></pre>

**Comment by lossius** [comment]
Yes, a parameter per definition has a state. An instantiation this state is set by the default attribute, and can then later on be overridden by the model preset. If no default value is set, it defaults to :
 
0.0 for type decimal, array and generic
0 for type integer and boolean
"none" for type string

**Comment by bltzr** [comment]
I don't think this should be closed, as the behavior is quite counter-intuitive IMHO - we discussed this at the last BoD, and the (temporary) conclusion was that we should improve the init mechanism
I understand that, from the internal coding POV this makes sense, but it's very strange that something is output when nothing is set in j.parameter's inspector 
IMHO, we're not done with this problem yet

**Comment by bltzr** [comment]
should we discuss that again at the next BoD ?

**Comment by lossius** [comment]
I'll close this issue again. We should make another issue (unless it has already been made) for a feature request to handle overriding initialisation values in a more elegant way, so that models with presets will prevent j.parameter from outputting its default value in case the parameter is also set from the default preset But this is a feature for a version past 0.6, and the current behaviour is what we have decided to have for the time being.
