### ISSUE TITLE
Re-implement hipnoscope as a data model for interpolation of presets

### ISSUE THREAD

**Issue by lossius** [jamoma/JamomaMax#873]
This could then be combined with other models to recreate (or invente new) Hipno-like plugins

**Comment by bltzr** [comment]
IMHO this should be based on j.cue, so we have a more open namespace management than with presets…

Though, in order to do this, we need to optimize cue interpolations *a lot* : it is currently extermely slow (so slow that we had to use pattrstorage when trying to interpolate between cues containing less than a hundred parameters…)
see #875

**Comment by lossius** [comment]
Maybe the design could be open-ended enough to cater for both?

**Comment by bltzr** [comment]
sure...

**Comment by lossius** [comment]
This is done, and have lead to new models, including an amogwai model.
