### ISSUE TITLE
j.view: Naming error with views within views

### ISSUE THREAD

**Issue by lossius** [jamoma/JamomaMax#920]
Embedding views within views used to work (see e.g. the ICMC / SMC paper from last year), and one could have subviews inherit their name from the main view, or the name of the embedded view could be set explicitly with an "address" message. As of lately this is broken. Here are two examples illustrating the problem:

1. Open equalizer~.model.maxhelp
2. Click the button in upper right corner of the eq model to bring up a second view of the equalizer

Result: The new view was supposed to be named the same: "/eq". Instead it's named "/eq/eq".

And here's another example of the same issue:

1. Open output~.model.maxhelp
2. Click the button in the upper right corner of the output module. Thiss brings up a limiter view.

Result: The limiter is supposed to be named "/output/limiter". Instead it is named "no_model_address".

**Comment by theod** [comment]
if you change the argument into equalizer.view bpatcher to /eq (instead of eq only which is a relative address to it is appended the view address).

I would not say it is a bug.
some changes don't not allow to put relative addresses here (or at least it is allowed but the result is not what you want to do).

I add @bltzr and @jln- to this discussion to get their point of view before to close.

**Comment by theod** [comment]
and this is not explaining why there is /no_model_address in the limiter view ...

**Comment by theod** [comment]
sorry ... forget about what I said before.
this commit mentioned above resolves the both troubles so you can keep the argument as it is.

**Comment by theod** [comment]
@jln- : notice that now in .module patchers it is not needed to put a #1 as argument of the .model patcher and for the .view bpatcher ! 

now the j.model inside .model patcher and the j.view inside the .view bpatcher will automagically read all the arguments written into the top .module patcher (so it will read the name but also any given attribute like @priority, @amenities, ...)

I'll warn the list in order to ask people to update .module patchers but if you already document the way to build a module you should update this (even if it is not urgent are the #1 will simply be ignored).

**Comment by jln-** [comment]
Noted. But you set me a ticket to document this right ?

**Comment by theod** [comment]
yes I forgot about it https://github.com/jamoma/JamomaMax/issues/914

**Comment by lossius** [comment]
Thanks a lot, Theo, I have tested with a bunch of patchers that have views within views, and they all seem to work now. However, if I open dbap=.model.maxhelp, I now get a bunch of error messages in the Max window:

    Invalid argument(s) for view
    Invalid argument(s) for view
    j.remote_array: Jamoma cannot register multiple objects with the same OSC identifier (speakers/speaker.1/position).  Using speakers/speaker.1/position.1 instead.
    Invalid argument(s) for view
    Invalid argument(s) for view
    Invalid argument(s) for view

I believe it woudl be a good idea to get rid of these before we close this issue. Reassigning to @theod

**Comment by lossius** [comment]
(In the above post I'm not concerned with the j.remote_array warning, but rather the ones relating to view.)

**Comment by theod** [comment]
the "Invalid argument(s) for view" error in a j.dbap error.
it is not related to the subscription mechanism but to the use of the view message of j.dbap.
I open a new issue for this
