### ISSUE TITLE
j.modular: activity attribute should be renamed active

### ISSUE THREAD

**Issue by lossius** [jamoma/JamomaMax#930]
We use "active" attribute in many places in Jamoma, but j.modular instead has an "activity" attribute.

In one way it could be argued that j.modular can monitor activity or not, but you could just as well rephrase and say that either monitoring is active or not. This will be a small step towards a more unified interface within Jamoma. For this reason I suggest that we rename this attribute.

**Comment by reno-** [comment]
The function of this attribute is to enable/disable printing to the max console. So maybe ‘print’ or ‘monitor' might be a more descriptive name?
We should considering all Jamoma models where a ‘print’/‘monitor’ attribute could be an enhancement, like mouse, midiin etc…

From my point of view, ‘active’ should be reserved for enabling/disabling the whole model and in this case it could be used to open/close the UDP connection.

**Comment by theod** [comment]
+1 and I would vote for 'monitor'

**Comment by jln-** [comment]
+1 on monitor

**Comment by reno-** [comment]
My vote will go to 'print' as we have a print object in Max that doing this job.

**Comment by theod** [comment]
I understand the Max point of view but actually 'activity' is the name of an attribute into the C++ TTApplication class to enable the report of each incoming or outcoming network messages into read-only attributes called 'activity/in' and 'activity/out'. 

Notice the function of those attributes *is not* to print messages into the Max console as they are pure C++ attribute. As you know we we need to observe those attributes using a [j.receive :activity/in] or [j.receive :activity/out] to print network messages but any kind of processing can be done instead of printing them.

So I find 'monitor', 'monitor/in' and 'monitor/out' more understandable but what ever the choice we do we'll need to find a consistency for those 3 attributes.

But why not use 'print' for j.minuit_device as it is Max patcher.

**Comment by tap** [comment]
If it is to be renamed, then I would like to request that it be renamed *immediately*.  I am opposed to renaming it after the 1.0 release (which I now anticipate in the next 1-2 weeks).

**Comment by theod** [comment]
done !
