### ISSUE TITLE
dbap=.model.maxhelp : "Invalid argument(s) for view" error

### ISSUE THREAD

**Issue by theod** [jamoma/JamomaMax#945]
it seems the view message of j.dbap is not well formated at some point.

**Comment by lossius** [comment]
I'm not sure what you mean by well formatted? I suspect that this is a message posted because more than one view is associated with the same model, but without providing specific and discriminating names for each of the views, so that when the views gest added to the node tree as "view models" several of them have the same name.

Do this message need to be posted as a red error message? Couldn't it rather just be be posted as a warning so that it doesn't look as severe? If I know that I will not be dealing with the views as models, I don't want to have to cater for it at all (convention over configuration) and the fact that there are naming conflicts won't be harming me, so what do I care about the stuff in the Max window?

**Comment by theod** [comment]
no ! it is an error posted by the j.dbap *external*. you can look at the code here : https://github.com/jamoma/JamomaMax/blob/master/source/j.dbap/j.dbap.cpp from line 431 to 474.

the j.dbap external have a "view" message with a specific syntax and I guess at some point when stuff are loaded something wrong is sent to the j.dbap.
