### ISSUE TITLE
foreground_mask.model uses cv.jit.ravg external

### ISSUE THREAD

**Issue by theod** [jamoma/JamomaMax#990]
is not problematic to keep such a dependency ?
or maybe this means we should add cv.jit library to the Max dependencies ?

**Comment by jln-** [comment]
I think @reno- already made a ticket about this. I dont remember the conclusion of the discussion, though...

**Comment by theod** [comment]
you're right this external is mentioned here : https://github.com/jamoma/JamomaMax/issues/686

**Comment by theod** [comment]
but xray is part of JamomaMaxDependencies repository while cv.jit is not so I'm not sure of what is the policy about dependencies ... maybe @lossius and @tap have an opinion ?
and what about pointing to the Package Manager is that case as cv.jit is available ?

**Comment by tap** [comment]
I agree that we should point to the package manager instead of including in dependencies.

It would also be nice if we could handle the error when it is missing.  Can it be done by creating an abstraction using the `error` object that (when it sees an error about the xray or icst etc object) pops up a dialog telling you what to do?

**Comment by theod** [comment]
I can try to make a new j.dependency component to handle that.

**Comment by theod** [comment]
I can't find any external that pop up a simple warning. the [dialog] external have a text field which is not useful here. any idea ?

**Comment by theod** [comment]
I found a solution...

**Comment by theod** [comment]
I tried but the main problem is that the error object cannot catch errors at loading time it self !
so if it works when patching but not the loading the model...

**Comment by theod** [comment]
[dependency.zip](https://github.com/jamoma/JamomaMax/files/64192/dependency.zip)

here is what I tried to do in case you have an idea how to open the warning window when loading j.dependency.maxhelp.

**Comment by tap** [comment]
The problem appears to be that the `foo` object is created before the `j.dependency` object.  
This problem is then amplified by the use of `loadmess` which doesn't fire until even later.

There is a two part solution:

* Eliminate the `loadmess` and give the `error` object an argument of `1`.  I can see that this not documented, so I'll fix the Max documentation for that.  Giving an arg of 1 will turn on the error object immediately (sooner than if you use `loadmess`).
* The `j.dependency` instance needs to be in the patcher with the `foo` object.  Max loads the patcher in z-order, deepest first and then working upward to the top-level patcher.  So by having the `j.dependency` in the top-level patcher it is loaded too late to catch the deeper-embedded `foo`.

That should work.  It's great that you've tackled this problem!

**Comment by theod** [comment]
as you said the first part of the solution resolved the problem when j.dependency is at the same level and instantiated before foo.test. I've updated the maxhelp to explain this constraint. Is it ok to add it to the package ?

[dependency.zip](https://github.com/jamoma/JamomaMax/files/64246/dependency.zip)

**Comment by tap** [comment]
Yes, please!

best,
  Tim
